### ISSUE TITLE
how to retrieve portrait url

### ISSUE THREAD

**Issue by mouneyrac** [tpavlek/oauth2-bnet#3]
to retrieve portrait url in the entity class:
$this->portrait_url = substr($attributes['portrait']->url, 0, strpos($attributes['portrait']->url, '-'))
            . '-' . $attributes['portrait']->offset . ".jpg";

**Comment by tpavlek** [comment]
I just released 3.0.1 adding this feature. Thanks for the contribution!

**Comment by mouneyrac** [comment]
whao it was fast, thanks :)
